---

- name: backup /etc/resolv.conf if not already done
  vars:
    mysrc: "/etc/resolv.conf"
    mydst: "/etc/resolv.conf.orig"
  tasks:
    - name: Check if file exists
      ansible.builtin.stat:
        path: "{{ mydst }}"
      register: check_file_name
- name: print debug
      ansible.builtin.debug:
        var: check_file_name
- name: copy file to backup name
      ansible.builtin.copy:
        remote_src: true
        src: "{{ mysrc }}"
        dest: "{{ mydst }}"
      when: check_file_name.stat.exists == False
- name: Remove old file
      ansible.builtin.file:
        path: "{{ mysrc }}"
        state: absent
      when: check_file_name.stat.exists == False

- name: set /etc/resolv.conf as symlink to /run/systemd/resolve/stub-resolv.conf
  file:
    src: "/run/systemd/resolve/stub-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link

